FROM ubuntu:18.04
MAINTAINER showwin <showwin_kmc@yahoo.co.jp>

ENV LANG en_US.UTF-8

RUN apt-get update
RUN apt-get install -y wget sudo less vim

# ishocon ユーザ作成
RUN groupadd -g 1001 ishocon && \
    useradd  -g ishocon -G sudo -m -s /bin/bash ishocon && \
    echo 'ishocon:ishocon' | chpasswd
RUN echo 'ishocon ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# MySQL のインストール
RUN ["/bin/bash", "-c", "debconf-set-selections <<< 'mysql-server mysql-server/root_password password ishocon'"]
RUN ["/bin/bash", "-c", "debconf-set-selections <<< 'mysql-service mysql-server/mysql-apt-config string 4'"]
RUN apt-get install -y mysql-server

# Nginx のインストール
RUN apt-get install -y nginx
COPY admin/ssl/ /etc/nginx/ssl/
COPY admin/config/nginx.conf /etc/nginx/nginx.conf

# Ruby のインストール
RUN apt-get install -y git ruby-dev libssl-dev libreadline-dev gcc make libmysqlclient-dev && \
    git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
ENV PATH "$HOME/.rbenv/bin:$PATH"
RUN eval "$(/root/.rbenv/bin/rbenv init -)" && \
    git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build && \
    /root/.rbenv/bin/rbenv install 2.5.1 && /root/.rbenv/bin/rbenv rehash && /root/.rbenv/bin/rbenv global 2.5.1

USER ishocon

# アプリケーション
RUN mkdir /home/ishocon/data /home/ishocon/webapp
COPY admin/ishocon2.dump.tar.bz2 /home/ishocon/data/ishocon2.dump.tar.bz2
COPY webapp/ /home/ishocon/webapp
COPY admin/config/bashrc ~/.bashrc
RUN cd /home/ishocon/webapp/ruby && sudo gem install bundler && bundle install
RUN sudo chown -R ishocon:ishocon ~/

COPY docker/start_app.sh /docker/start_app.sh

WORKDIR /home/ishocon
EXPOSE 443
