FROM ubuntu:18.04
MAINTAINER showwin <showwin_kmc@yahoo.co.jp>

RUN apt-get update
RUN apt-get install -y wget mysql-client git curl libssl-dev libreadline-dev gcc make libmysqlclient-dev

# Go のインストール
RUN wget https://dl.google.com/go/go1.10.2.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.10.2.linux-amd64.tar.gz
ENV PATH $PATH:/usr/local/go/bin
ENV GOROOT /usr/local/go
ENV GOPATH $HOME/.local/go
ENV PATH $PATH:$GOROOT/bin

# Python のインストール
RUN git clone https://github.com/pyenv/pyenv.git ~/.pyenv && \
    PYENV_ROOT="$HOME/.pyenv" && PATH="$PYENV_ROOT/bin:$PATH" && \
    eval "$(pyenv init -)" && \
    pyenv install 3.6.5 && pyenv global 3.6.5 && \
    cd && curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py && rm get-pip.py

COPY admin/benchmarker /root/benchmarker
COPY admin/config/bashrc /root/.bashrc

# build benchmark
RUN cd /root && go get -t -d -v ./... && go build -o benchmark benchmarker/*.go

COPY admin/bench_app /root/bench_app
RUN LC_ALL=C.UTF-8 && LANG=C.UTF-8 && cd /root/bench_app && \
    /root/.pyenv/shims/pip install -r requirements.txt

COPY admin/bench_app/start_bench_app.sh /docker/start_bench_app.sh

WORKDIR /root/bench_app

EXPOSE 80

CMD ["/root/.pyenv/shims/uwsgi", "app.ini"]
